### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [zellerin/http2#1]
Building with SBCL 2.2.10.127-d9429f05a / ASDF 3.3.5 for quicklisp dist creation.

Trying to build commit id 0020ee1851dfe489271b3098ef81096ea36dc9ae

*http2* fails to build with the following error:

```
Unhandled PACKAGE-DOES-NOT-EXIST in thread #<SB-THREAD:THREAD "main thread" RUNNING {10016D0003}>: The name "ALEXANDRIA" does not designate any package.

```

*http2/all* fails to build with the following error:

```
Unhandled PACKAGE-DOES-NOT-EXIST in thread #<SB-THREAD:THREAD "main thread" RUNNING {10016D0003}>: The name "ALEXANDRIA" does not designate any package.

```

*http2/test* fails to build with the following error:

```
Unhandled PACKAGE-DOES-NOT-EXIST in thread #<SB-THREAD:THREAD "main thread" RUNNING {10016D0003}>: The name "ALEXANDRIA" does not designate any package.

```

[Full log here](http://report.quicklisp.org/2022-12-11/failure-report/http2.html)

**Comment by zellerin** [comment]
Fixed by fd6a04b9d9a98c9de76b836fd93a09d32762b5ae.
