### ISSUE TITLE
Unable to build from latest source

### ISSUE THREAD

**Issue by rome-user** [zellerin/http2#2]
After running `(ql:quickload 'http2/server)`, the following error appears in the REPL.
```
; caught ERROR:
;   READ error during COMPILE-FILE:
;   
;     Symbol "GET-SELECTED-ALPN-PROTOCOL" not found in the CL+SSL package.
;   
;       Line: 53, Column: 61, File-Position: 2045
;       Stream: #<SB-INT:FORM-TRACKING-STREAM for "file ~/quicklisp/local-projects/http2/tls/server.lisp" {1003D64E83}>
```
Is there a possibility this function was removed from the latest CL+SSL?

**Comment by zellerin** [comment]
Hmm, I cannot reproduce this, even after (ql:update-all-dists).

Can you check that the ssl in use is in `~/quicklisp/dists/quicklisp/software/cl+ssl-20230214-git/`, e.g. by  `(asdf:component-pathname (asdf:find-system "cl+ssl"))`? What I have in mind is the version.

If so, can you check whether the function is defined in "src/streams.lisp" there?
